#!/usr/bin/env bash
# CustomPiOS module : supervisor
# @RyanBalfanz

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

source /common.sh
install_cleanup_trap

apt --assume-yes install supervisor
